# Generated by Django 5.2 on 2025-04-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_albergue',
            field=models.BooleanField(default=False, verbose_name='albergue'),
        ),
    ]
