# Generated by Django 5.2 on 2025-04-22 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_is_albergue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albergue',
            name='direccion',
        ),
        migrations.AddField(
            model_name='albergue',
            name='calle',
            field=models.CharField(default='Desconocida', max_length=200),
        ),
        migrations.AddField(
            model_name='albergue',
            name='codigo_postal',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='albergue',
            name='estado',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='albergue',
            name='municipio',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='albergue',
            name='numero_exterior',
            field=models.CharField(default='SN', max_length=20),
        ),
        migrations.AddField(
            model_name='albergue',
            name='referencias',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='albergue',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
