# Generated by Django 5.2 on 2025-04-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_albergue_direccion_albergue_calle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albergue',
            old_name='capacidad',
            new_name='capacidad_maxima',
        ),
        migrations.RemoveField(
            model_name='albergue',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='albergue',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='albergue',
            name='numero_exterior',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='address',
        ),
        migrations.AddField(
            model_name='albergue',
            name='alcaldia',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albergue',
            name='animales_actuales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='albergue',
            name='entidad',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albergue',
            name='num_ext',
            field=models.CharField(default='Desconocido', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albergue',
            name='num_int',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='albergue',
            name='calle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='albergue',
            name='codigo_postal',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='albergue',
            name='servicios',
            field=models.JSONField(default=list),
        ),
    ]
