# Generated by Django 5.1.7 on 2025-07-01 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopciones', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perroenadopcion',
            name='albergue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.albergue'),
        ),
        migrations.AddField(
            model_name='perroenadopcion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='perro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.perroenadopcion'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
