# Generated by Django 5.1.7 on 2025-07-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_Perro', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perroperdido',
            name='tamaño',
            field=models.CharField(max_length=20),
        ),
    ]
